# This file was generated by GoReleaser. DO NOT EDIT.
cask "target" do
  name "target"
  desc ""
  homepage "https://github.com/netdata-be/target-cli"
  version "2.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "target"

  on_macos do
    url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_darwin_all.tar.gz"
    sha256 "fe28a8c7bf410d6e418b8d6a9f59b073bf5db4acdd28d7722e4db52ce0818ef3"
  end

  on_linux do
    on_intel do
      url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_linux_amd64.tar.gz"
      sha256 "51d36ff4e8703c15274d1c5baa3adaae00f4d00b0a005014db7bbbd5630d7712"
    end
    on_arm do
      url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_linux_arm64.tar.gz"
      sha256 "be6c7e86b900bcf4474266d99a103174ebe0e62a5c0628b73300694744674129"
    end
  end

  # No zap stanza required
end
