# This file was generated by GoReleaser. DO NOT EDIT.
cask "target" do
  name "target"
  desc ""
  homepage "https://github.com/netdata-be/target-cli"
  version "2.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "target"

  on_macos do
    url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_darwin_all.tar.gz"
    sha256 "71bb55af4c12206521096372fd2596d0715f6d21771057e42fe697cba756330f"
  end

  on_linux do
    on_intel do
      url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_linux_amd64.tar.gz"
      sha256 "d7c0896e1ae2a2964c74ae8186a5926ef4c595b1a971d7286e93e31bc956d450"
    end
    on_arm do
      url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_linux_arm64.tar.gz"
      sha256 "3700c0e4361b299773bb6c45f0ab6d507c6e29047f158f5155ca6431163d3bf5"
    end
  end

  # No zap stanza required
end
