# This file was generated by GoReleaser. DO NOT EDIT.
cask "target" do
  name "target"
  desc ""
  homepage "https://github.com/netdata-be/target-cli"
  version "2.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "target"

  on_macos do
    url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_darwin_all.tar.gz"
    sha256 "791a2b7ca78d4edb74a0d5bb7f7b97b00a87db78a6adf7a0bc5a0cb5c18445e5"
  end

  on_linux do
    on_intel do
      url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_linux_amd64.tar.gz"
      sha256 "26bf1e911b8cf96e32a3bb2216a5608d665bc3b2bcb0f08b390da2423471136e"
    end
    on_arm do
      url "https://github.com/netdata-be/target-cli/releases/download/v#{version}/target-cli_#{version}_linux_arm64.tar.gz"
      sha256 "2dcd6a79911252df76d6bdb754a79b4cc7104fdbd241a0fbb4767bbdb626f5da"
    end
  end

  # No zap stanza required
end
